### PR TITLE
Implemented power feature and created unit tests

### LINKED ISSUE #4: Implement the Power feature
- Implement the Power of a number feature

### PR DESCRIPTION
**Pull request by paulgray01**
added power function with user input and resulting output. also wrote two unit tests to test power function

### CODE REVIEW

**Review by anshuldhariwal — CHANGES_REQUESTED** [review]
Hey Paul, the code and comments look perfect. Can you remove the test_power.py and have it under a new full request?

**Comment by paulgray01** [comment]
> Hey Paul, the code and comments look perfect. Can you remove the test_power.py and have it under a new full request?

yea I can do that

**Comment by paulgray01** [comment]
okay, I separated the two files into their own PRs, you can re-review

**Review by anshuldhariwal — APPROVED** [review]
Looks perfect!

**Pull request merged**
